[package]
name = "aoc_helper"
version = "0.2.0"
authors = ["antonin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
